GET http://localhost:5000/delta-smart-3efb4/us-central1/microservice/images?page=1&limit=5

# GET http://localhost:5000/delta-smart-3efb4/us-central1/microservice/images/NszjlQ4FFVQlI94YVs7O

# GET https://us-central1-delta-smart-3efb4.cloudfunctions.net/microservice/images